version: 0.0
os: linux
files:
  - source: /                    # Caminho de origem dos arquivos do repositório
    destination: /home/ubuntu/ec2aws  # Destino no EC2 onde os arquivos serão copiados
permissions:
  - object: /home/ubuntu/ec2aws/*
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/git_pull.sh
      timeout: 300

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180

  ApplicationStart:
    - location: scripts/migrate.sh
      timeout: 180

  ValidateService:
    - location: scripts/restart.sh
      timeout: 60

