version: 0.2

phases:
  pre_build:
    commands:
      - echo "Atualizando o código com git pull"
      - git pull origin main
  build:
    commands:
      - echo "Reiniciando o Nginx"
      - sudo systemctl restart nginx
      - echo "Reiniciando o Gunicorn"
      - sudo systemctl restart gunicorn
