version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ec2aws
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/migrate.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/restart.sh
      timeout: 300
      runas: ubuntu

