version: 0.0
os: linux
files:
  - source: /           # Copia todos os arquivos da raiz do repositório, incluindo manage.py
    destination: /home/ubuntu/ec2aws/
  - source: /sgo/       # Copia o conteúdo do diretório sgo (configuração do Django)
    destination: /home/ubuntu/ec2aws/sgo/
  - source: /core/      # Copia o conteúdo do diretório core (templates, static, etc.)
    destination: /home/ubuntu/ec2aws/core/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
    - location: scripts/migrate_database.sh
      timeout: 180
