version: 0.2

phases:
  install:
    commands:
      # Instala dependências do sistema, se necessário
      echo "Instalando dependências do sistema"
      sudo apt-get update -y
      sudo apt-get install -y git

  pre_build:
    commands:
      # Se você precisar de um 'git pull' para atualizar o repositório antes de compilar, adicione aqui
      echo "Realizando git pull"
      cd /path/to/your/project/directory
      git pull origin main

  build:
    commands:
      echo "Instalando dependências do Python"
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Comandos adicionais de construção do projeto, se necessário
      echo "Construindo a aplicação Django"

  post_build:
    commands:
      echo "Reiniciando o servidor"
      # Exemplo: reiniciar o servidor
      sudo systemctl restart nginx
      # Ou qualquer outro comando para reiniciar seu servidor
      sudo systemctl restart gunicorn

artifacts:
  files:
    - '**/*'
  discard-paths: yes
