version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Install python dependencies"
      - python -m pip install --upgrade pip
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - echo "Install dependencies"
      - ./install_dependencies.sh  # Adicionando script de instalação

  pre_build:
    commands:
      - echo "Updating codebase"
      - git pull origin main || exit 1  # Atualizando o código com git pull
      - source venv/bin/activate  # Ativando ambiente virtual, se necessário

  build:
    commands:
      - echo "Running migrations"
      - python manage.py migrate  # Rodando migrações do Django

  post_build:
    commands:
      - echo "Restarting Gunicorn and Nginx"
      - sudo /bin/systemctl restart gunicorn  # Reiniciando o Gunicorn
      - sudo /bin/systemctl restart nginx  # Reiniciando o Nginx
