version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências do Python"
      - python -m pip install --upgrade pip

  pre_build:
    commands:
      - echo "Fazendo git pull para garantir o código mais recente"
      - git pull origin main

  build:
    commands:
      - echo "Instalando dependências do Django"
      - pip install -r requirements.txt

  post_build:
    commands:
      - echo "Build finalizado"
