version: 0.2

phases:
  install:
    commands:
      - echo "Install python dependencies"
      - python -m pip install --upgrade pip
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  build:
    commands:
      - echo "Git Pull"
      - git pull origin main  # Certifique-se de substituir "main" pelo nome correto do seu branch
      - echo "Restart server"
      - sudo systemctl restart nginx  # Comando para reiniciar o Nginx, se for o seu servidor web

  post_build:
    commands:
      - echo "Post build steps"
