# Generated by Django 5.0.7 on 2025-02-03 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sobrenome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "telefone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="O número de telefone deve ter o formato DDD + número (sem espaços ou caracteres especiais).",
                                regex="^\\d{2}\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("cidade", models.CharField(max_length=100)),
                (
                    "servicos",
                    models.CharField(
                        help_text="Lista de serviços separados por vírgula",
                        max_length=500,
                    ),
                ),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
